# Generated by Django 5.0.4 on 2024-04-08 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinsiyetler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinsiyet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etkinlikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_adi', models.CharField(max_length=200)),
                ('etkinlik_gunu', models.DateField()),
                ('etkinlik_saati', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokantalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokanta', models.CharField(max_length=200)),
                ('il', models.CharField(max_length=100)),
                ('ilçe', models.CharField(max_length=100)),
                ('konum', models.CharField(max_length=500)),
                ('lokanta_iletisim', models.CharField(max_length=50)),
                ('yetkilisi', models.CharField(max_length=100)),
                ('yetkili_iletisim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Odeme_Yontemleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_yontemi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uyruklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyruk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yerler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Geziciler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('dogum', models.DateField()),
                ('kimlik_no', models.CharField(max_length=100)),
                ('e_posta', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=50)),
                ('yakin_ad', models.CharField(max_length=100)),
                ('yakin_tel', models.CharField(max_length=50)),
                ('cinsiyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.cinsiyetler')),
                ('uyruk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.uyruklar')),
            ],
        ),
        migrations.CreateModel(
            name='Geziler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gezi', models.CharField(max_length=500)),
                ('baslangic', models.DateTimeField()),
                ('bitis', models.DateTimeField()),
                ('ucak_kalkis_yeri', models.CharField(max_length=200)),
                ('ucak_kalkis_saati', models.DateField()),
                ('ucak_inis_yeri', models.CharField(max_length=200)),
                ('ucak_inis_saati', models.DateField()),
                ('etkinlikler', models.ManyToManyField(to='geziuygulamasi.etkinlikler')),
                ('gezicisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.geziciler')),
            ],
        ),
        migrations.CreateModel(
            name='Gezginler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('dogum', models.DateField()),
                ('pasaport_no', models.CharField(max_length=100)),
                ('e_posta', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=500)),
                ('yakin_ad', models.CharField(max_length=100)),
                ('yakin_tel', models.CharField(max_length=50)),
                ('tutar', models.CharField(max_length=100)),
                ('odendi', models.BooleanField(default=False)),
                ('cinsiyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.cinsiyetler')),
                ('odeme_yontemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.odeme_yontemleri')),
                ('uyruk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.uyruklar')),
            ],
        ),
    ]
