# Generated by Django 5.0.4 on 2024-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gezginler',
            name='yakinlik',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geziciler',
            name='yakinlik',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
