# Generated by Django 5.0.4 on 2024-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0002_gezginler_yakinlik_geziciler_yakinlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='geziciler',
            name='dil',
            field=models.ManyToManyField(to='geziuygulamasi.diller'),
        ),
    ]
