# Generated by Django 5.0.4 on 2024-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0003_diller_geziciler_dil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yakinlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakinlik', models.CharField(max_length=50)),
            ],
        ),
    ]
