# Generated by Django 5.0.4 on 2024-04-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0004_yakinlar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yakinlar',
            new_name='Yakinliklar',
        ),
    ]
