# Generated by Django 5.0.4 on 2024-04-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0005_rename_yakinlar_yakinliklar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gezginler',
            name='yakinlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.yakinliklar'),
        ),
    ]
