# Generated by Django 5.0.4 on 2024-04-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0006_alter_gezginler_yakinlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doviz', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='gezginler',
            name='odeme_yontemi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.odeme_yontemleri'),
        ),
        migrations.AddField(
            model_name='gezginler',
            name='doviz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.doviz'),
            preserve_default=False,
        ),
    ]
