# Generated by Django 5.0.4 on 2024-04-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0007_doviz_alter_gezginler_odeme_yontemi_gezginler_doviz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gezginler',
            name='odendi',
            field=models.BooleanField(default=True),
        ),
    ]
