# Generated by Django 5.0.4 on 2024-04-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0008_alter_gezginler_odendi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geziciler',
            name='yakinlik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.yakinliklar'),
        ),
    ]
