# Generated by Django 5.0.4 on 2024-04-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0010_alter_geziciler_yakinlik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geziler',
            name='baslangic',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='bitis',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='etkinlikler',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='gezicisi',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='ucak_inis_saati',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='ucak_inis_yeri',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='ucak_kalkis_saati',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='ucak_kalkis_yeri',
        ),
        migrations.AlterField(
            model_name='geziler',
            name='gezi',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Takimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.DateTimeField()),
                ('bitis', models.DateTimeField()),
                ('gidis_ucagi', models.CharField(max_length=100)),
                ('gidis_ucus_no', models.CharField(max_length=50)),
                ('ucak_kalkis_yeri', models.CharField(max_length=200)),
                ('ucak_kalkis_gunu', models.DateTimeField()),
                ('donus_ucagi', models.CharField(max_length=100)),
                ('donus_ucus_no', models.CharField(max_length=50)),
                ('ucak_inis_yeri', models.CharField(max_length=200)),
                ('ucak_inis_gunu', models.DateTimeField()),
                ('etkinlikler', models.ManyToManyField(to='geziuygulamasi.etkinlikler')),
                ('gezi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.geziler')),
                ('gezicisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.geziciler')),
            ],
        ),
        migrations.AddField(
            model_name='gezginler',
            name='takim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.takimlar'),
        ),
    ]
