# Generated by Django 5.0.4 on 2024-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0011_remove_geziler_baslangic_remove_geziler_bitis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlikler',
            name='etkinlik_saati',
        ),
        migrations.RemoveField(
            model_name='takimlar',
            name='etkinlikler',
        ),
        migrations.AddField(
            model_name='geziler',
            name='gezi_ayrintilari',
            field=models.ManyToManyField(to='geziuygulamasi.etkinlikler'),
        ),
        migrations.AlterField(
            model_name='etkinlikler',
            name='etkinlik_gunu',
            field=models.DateTimeField(),
        ),
    ]
