# Generated by Django 5.0.4 on 2024-04-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0013_ucaklar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucus_Alanlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucus_alani', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='takimlar',
            name='donus_ucagi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donus_ucagi', to='geziuygulamasi.ucaklar'),
        ),
        migrations.AlterField(
            model_name='takimlar',
            name='gidis_ucagi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gidis_ucagi', to='geziuygulamasi.ucaklar'),
        ),
        migrations.AlterField(
            model_name='takimlar',
            name='ucak_inis_yeri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucak_inis_yeri', to='geziuygulamasi.ucus_alanlari'),
        ),
        migrations.AlterField(
            model_name='takimlar',
            name='ucak_kalkis_yeri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucak_kalkis_yeri', to='geziuygulamasi.ucus_alanlari'),
        ),
    ]
