# Generated by Django 5.0.4 on 2024-04-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0014_ucus_alanlari_alter_takimlar_donus_ucagi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takimlar',
            name='ucak_inis_gunu',
        ),
        migrations.RemoveField(
            model_name='takimlar',
            name='ucak_inis_yeri',
        ),
        migrations.RemoveField(
            model_name='takimlar',
            name='ucak_kalkis_gunu',
        ),
        migrations.RemoveField(
            model_name='takimlar',
            name='ucak_kalkis_yeri',
        ),
        migrations.AddField(
            model_name='takimlar',
            name='donus_ucak_inis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='donus_ucak_inis_yeri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donus_ucak_inis_yeri', to='geziuygulamasi.ucus_alanlari'),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='donus_ucak_kalkis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='donus_ucak_kalkis_yeri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donus_ucak_kalkis_yeri', to='geziuygulamasi.ucus_alanlari'),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='gidis_ucak_inis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='gidis_ucak_inis_yeri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gidis_ucak_inis_yeri', to='geziuygulamasi.ucus_alanlari'),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='gidis_ucak_kalkis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='gidis_ucak_kalkis_yeri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gidis_ucak_kalkis_yeri', to='geziuygulamasi.ucus_alanlari'),
        ),
        migrations.AlterField(
            model_name='takimlar',
            name='donus_ucagi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donus_ucagi', to='geziuygulamasi.ucaklar'),
        ),
    ]
