# Generated by Django 5.0.4 on 2024-04-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0015_remove_takimlar_ucak_inis_gunu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Araclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurulus', models.CharField(max_length=200)),
                ('kurulus_iletisim', models.CharField(max_length=50)),
                ('yetkilisi', models.CharField(max_length=100)),
                ('yetkili_iletisim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Konaklamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konaklama', models.CharField(max_length=200)),
                ('il', models.CharField(max_length=100)),
                ('ilçe', models.CharField(max_length=100)),
                ('konum', models.CharField(max_length=500)),
                ('konaklama_iletisim', models.CharField(max_length=50)),
                ('yetkilisi', models.CharField(max_length=100)),
                ('yetkili_iletisim', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='etkinlikler',
            name='etkinlik_gunu',
        ),
        migrations.RemoveField(
            model_name='geziler',
            name='gezi_ayrintilari',
        ),
        migrations.AddField(
            model_name='geziler',
            name='gun_sayisi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='takim_adi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Etkinlik_Ayrintilari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_suresi', models.DateTimeField()),
                ('arac_plakasi', models.CharField(max_length=50, null=True)),
                ('arac_kurulusu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.araclar')),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.etkinlikler')),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.takimlar')),
                ('konaklama_yeri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.konaklamalar')),
            ],
        ),
    ]
