# Generated by Django 5.0.4 on 2024-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0016_araclar_konaklamalar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geziler',
            name='gece_sayisi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='geziler',
            name='gun_sayisi',
            field=models.IntegerField(null=True),
        ),
    ]
