# Generated by Django 5.0.4 on 2024-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0018_alter_geziler_gece_sayisi_alter_geziler_gun_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geziler',
            name='gece_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geziler',
            name='gun_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
