# Generated by Django 5.0.4 on 2024-04-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0019_alter_geziler_gece_sayisi_alter_geziler_gun_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='geziciler',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
