# Generated by Django 5.0.4 on 2024-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0020_geziciler_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='takimlar',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
