# Generated by Django 5.0.4 on 2024-04-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0021_takimlar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik_ayrintilari',
            name='arac_kurulusu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.araclar'),
        ),
        migrations.AlterField(
            model_name='etkinlik_ayrintilari',
            name='arac_plakasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etkinlik_ayrintilari',
            name='konaklama_yeri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.konaklamalar'),
        ),
    ]
