# Generated by Django 5.0.4 on 2024-04-11 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0022_alter_etkinlik_ayrintilari_arac_kurulusu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik_ayrintilari',
            name='yemek_yeri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.lokantalar'),
        ),
    ]
