# Generated by Django 5.0.4 on 2024-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0024_etkinlik_ayrintilari_ucus_alani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takimlar',
            name='baslangic',
        ),
        migrations.RemoveField(
            model_name='takimlar',
            name='bitis',
        ),
        migrations.AddField(
            model_name='takimlar',
            name='baslangic_ayi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='baslangic_gunu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='baslangic_yili',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='bitis_ayi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='bitis_gunu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='takimlar',
            name='bitis_yili',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
