# Generated by Django 5.0.4 on 2024-04-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0027_alter_takimlar_baslangic_alter_takimlar_bitis'),
    ]

    operations = [
        migrations.AddField(
            model_name='gezginler',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
