# Generated by Django 5.0.4 on 2024-04-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0028_gezginler_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gezginler',
            name='doviz',
        ),
        migrations.RemoveField(
            model_name='gezginler',
            name='odeme_yontemi',
        ),
        migrations.RemoveField(
            model_name='gezginler',
            name='odendi',
        ),
        migrations.RemoveField(
            model_name='gezginler',
            name='takim',
        ),
        migrations.RemoveField(
            model_name='gezginler',
            name='tutar',
        ),
        migrations.CreateModel(
            name='Gezginler_Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.CharField(max_length=100)),
                ('odendi', models.BooleanField(default=False)),
                ('doviz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.doviz')),
                ('gezgin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.gezginler')),
                ('odeme_yontemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.odeme_yontemleri')),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.takimlar')),
            ],
        ),
    ]
