# Generated by Django 5.0.4 on 2024-04-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0029_remove_gezginler_doviz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gezginler_odeme',
            name='takim',
        ),
        migrations.AddField(
            model_name='gezginler',
            name='takim',
            field=models.ManyToManyField(blank=True, null=True, to='geziuygulamasi.takimlar'),
        ),
    ]
