# Generated by Django 5.0.4 on 2024-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0030_remove_gezginler_odeme_takim_gezginler_takim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gezginler',
            name='takim',
            field=models.ManyToManyField(to='geziuygulamasi.takimlar'),
        ),
    ]
