# Generated by Django 5.0.4 on 2024-04-22 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0031_alter_gezginler_takim'),
    ]

    operations = [
        migrations.AddField(
            model_name='gezginler_odeme',
            name='takim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziuygulamasi.takimlar'),
        ),
    ]
