# Generated by Django 5.0.4 on 2024-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziuygulamasi', '0032_gezginler_odeme_takim'),
    ]

    operations = [
        migrations.AddField(
            model_name='geziciler',
            name='gobek_adi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
